apiVersion : apps/v1
kind: Deployment
metadata:
  name: xisenthilrajazurevotingappredis 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xisenthilrajazurevotingappredis
  template:
    metadata:
      labels:
        app: xisenthilrajazurevotingappredis 
    spec:
      containers:
        - name: xisenthilrajazurevotingappredis 
          image: redeyecontainerregistry.azurecr.io/xisenthilrajazurevotingappredis
          ports:
          - containerPort: 80